name: .NET

on:
  push:
    paths-ignore:
      - '**/README.md'
  pull_request:
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Restore
      run: dotnet restore ECommercePlatform/ECommercePlatform.sln
    - name: Build
      run: dotnet build ECommercePlatform/ECommercePlatform.sln --no-restore
    - name: Test
      run: dotnet test ECommercePlatform/ECommercePlatform.sln --no-build
